name: Grade Homework Workflow

on:
  issues:
    types: [opened, reopened]

jobs:
  main:
    name: Grade Homework
    runs-on: ubuntu-latest
    steps:
      - name: Grade Homework
        uses: usf-cs272-spring2022/action-homework-grade@main
        id: action-homework-grade
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
